import type { Metadata } from "next";  // Import Metadata type from Next.js
import { Inter } from "next/font/google";  // Import the Inter font from Google Fonts
import "./globals.css";  // Import global CSS
import Navbar from "./Components/Navbar";  // Import the Navbar component

// Set up the Inter font with the Latin subset
const inter = Inter({ subsets: ["latin"] });

// Define the page metadata (used for SEO and other page-related information)
export const metadata: Metadata = {
  title: "Create Next App",  // Title for the page
  description: "Generated by create next app",  // Description for the page
};

// Root layout component that wraps the entire app
export default function RootLayout({
  children,  // The content for the current page
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">  {/* Set the language of the document to English */}
      <body className={inter.className}>  {/* Apply the Inter font to the body */}
        <Navbar />  {/* Render the Navbar component inside the body */}
        {children}  {/* Render the children (page-specific content) */}
      </body>
    </html>
  );
}
